# Generated by Django 3.2 on 2024-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='ideal_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
