# Generated by Django 4.2.11 on 2024-03-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_remove_userfood_food_userfood_calories_userfood_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offset',
            field=models.TextField(blank=True, null=True),
        ),
    ]
