# Generated by Django 4.2.11 on 2024-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_user_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
